# Set update schedule for GitHub Actions
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    target-branch: 'main'
    versioning-strategy: 'increase-if-necessary'
    open-pull-requests-limit: 10
