network=regtest
debuglevel=info
rpclisten=0.0.0.0:10029
restlisten=0.0.0.0:8089
allow-public-uni-proof-courier=true
allow-public-stats=true

[Lnd]
lnd.host=lnd-alice:10009
lnd.macaroonpath=/root/.lnd/data/chain/bitcoin/regtest/admin.macaroon
lnd.tlspath=/root/.lnd/tls.cert

[Universe]
universe.public-access=rw
